name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      # You may pin to the exact commit or the version.
      # uses: cloudposse/github-action-docker-build-push@0192482637b94d39a2e76d4b01ab6f626c79e7cc
      uses: cloudposse/github-action-docker-build-push@1.13.1
      with:
        # Working directory
        image_name: nginx-sidecar-basic-auth # optional, default is 
        # Docker login
        login: andrea.intothevoid@gmail.com # optional, default is 
        # Docker password
        password: Gn0m0@i986!_ # optional, default is 
